### ISSUE TITLE
We found potential security vulnerabilities in your dependencies.

### ISSUE THREAD

**Issue by mem48** [SDCA-tool/sdca-website#29]
https://github.com/SDCA-tool/sdca-website/security/dependabot

FYI @mvl22 dealing with these is a requirment in the DfT code of conduct. These look simple to fix

**Comment by mvl22** [comment]
This was resolved in ee03c4d7f403670ed25f8a2e991f3bee51c74883, whereby the upgrade to the LayerViewer package resolved the problematic dependency. I finally found that the @mapbox/togeojson package has been forked to a maintained version.
