### ISSUE TITLE
Password blocks API?

### ISSUE THREAD

**Issue by mem48** [SDCA-tool/sdca-website#30]
@mvl22 the API is now not working when accessed directly e.g. 

https://dev.carbon.place/api/v1/locations.json?geojson=%7B%22type%22:%22FeatureCollection%22,%22features%22:[%7B%22type%22:%22Feature%22,%22properties%22:%7B%22intervention%22:%22cycle_lane_segregated%22,%22mode%22:%22Bicycle%22,%22intervention_class%22:%22New%20construction%22,%22intervention_name%22:%22New%20segregated%20cycle%20lane%22,%22infrastructure_type%22:%22transport%22,%22mode_class%22:%22Active%20travel%22%7D,%22geometry%22:%7B%22type%22:%22LineString%22,%22coordinates%22:[[0.066164,51.522798],[0.056346,51.51934],[0.04412,51.520377],[0.036155,51.518302],[0.031153,51.516919],[0.017816,51.517034],[0.00559,51.51519],[-0.000523,51.512193],[-0.000523,51.510463],[-0.008118,51.508388],[-0.017195,51.508734],[-0.022197,51.508849],[-0.026828,51.508849],[-0.031459,51.508734],[-0.040535,51.510233],[-0.042203,51.511732],[-0.049612,51.511155],[-0.053873,51.510694],[-0.057948,51.51127],[-0.067766,51.510809],[-0.075546,51.509887],[-0.081103,51.50931],[-0.085179,51.509195],[-0.092959,51.510579],[-0.10148,51.511501],[-0.106111,51.510925]]%7D%7D]%7D&showinput=true

I assume this has something to with the password being added to the site. Is there a way to provide the password via the HTTP request or have an API key etc?

The main use case is that I do testing and debugging on the R package by sending some pre-made geojsons to the API and then running the R code locally.

**Comment by mvl22** [comment]
The API is exempted from the login requirement in https://github.com/SDCA-tool/sdca-website-deploy/commit/009ad9315d4a37cc356bec608114fb78d3fe2f7f, though there was already a hotpatch to the same effect in place.

I think the result you got was actually an error 500 probably arising from the issue of too many lines possibly. You would have seen a login box otherwise.

**Comment by mvl22** [comment]
> I think the result you got was actually an error 500 probably arising from the issue of too many lines possibly.

As of 916c0c19ebfa55124e03c92a78b3587a01784035, any out-of-memory error is now caught and explicitly returned to the UI.
