### ISSUE TITLE
Switch from PAS 2080 to EN 17472

### ISSUE THREAD

**Issue by mem48** [SDCA-tool/sdca-website#33]
There has been a change in the published standards and PAS 2080 has been replaced with BS EN 17472. We need to update the tool to reflect this.

Initial changes are:

- [x] In the tool UI replace "PAS 2080" with "BS EN 17472"

![image](https://user-images.githubusercontent.com/15819577/174599519-78262739-dfc5-4ca7-8cff-1704956cf8d2.png)

- [x] New category "Land use change (A0)" added to graph and table, the R package will be updated to provide values for this

**Comment by mem48** [comment]
I realized there are some structural elements that used the PAS 2080 name. Such as https://github.com/SDCA-tool/sdca-data/blob/main/web_text/pas2080.csv I suggest leaving these for now and updating them in phase 2

**Comment by mvl22** [comment]
> In the tool UI replace "PAS 2080" with "BS EN 17472"

Done in 091a6d97d257fd5adf0daf9e621631141288cb36.

**Comment by mvl22** [comment]
> New category "Land use change (A0)" added to graph and table, the R package will be updated to provide values for this.

The website will just pick changes to that CSV up automatically. Can I suggest you put a ticket on that in your data/package repo, so that this web-related call can be closed.
