### ISSUE TITLE
Can't view website in Microsoft edge

### ISSUE THREAD

**Issue by mem48** [SDCA-tool/sdca-website#35]
The website doesn't load at all

Get a message

```
Unauthorized
This server could not verify that you are authorized to access the document requested. Either you supplied the wrong credentials (e.g., bad password), or your browser doesn't understand how to supply the credentials required.
```

Edge 103.0.1264.37 (64 Bit) Windows 10

**Comment by mvl22** [comment]
Did you use the right password? That's an access denied error.

The correct one is in the e-mail dated Sat, 28 May 2022 20:56:06 +0100.

The site is definitely loading for me on Edge/Win10.

**Comment by mem48** [comment]
On my computer Edge doesn't give a password prompt. I've also tried in private mode. I wonder if this is related to the switch to the new chromium-based edge?

For now, I'd say not a priority as the password is (hopefully) temporary and nobody uses edge anyway.

**Comment by mvl22** [comment]
What URL specifically are you trying?

Have you possibly got any other Incognito windows open? If you have one, that will cause the new one to have the same state.

I'm definitely getting a login as expected on Edge/Win10.

![Screenshot 2022-06-28 at 10 52 40](https://user-images.githubusercontent.com/361423/176150453-6de294ff-f5ba-447b-81cb-c80310b05e4e.png)

**Comment by mem48** [comment]
I've tried
https://dev.
http://dev.
and just dev.

But never get the sign-in popup

**Comment by mem48** [comment]
I only have one in private window open.

**Comment by mvl22** [comment]
I'm unable to reproduce the problem here still.

Using Edge/Win10 I do get the expected password protection. It behaves exactly the same as Chrome. This is as expected, since http auth is a webserver-level configuration so should affect all browsers equally.

Could you please try again and see if this is still happening for you?

**Comment by mvl22** [comment]
> What URL specifically are you trying?

NB Just a reminder that the API is exempted. So if you are trying that it will not give you a password. Hence why I was keen to have a specific complete URL to try to reproduce the issue.
