### ISSUE TITLE
Map copyright attribution for OS vector layer

### ISSUE THREAD

**Issue by mem48** [SDCA-tool/sdca-website#38]
The map should have the copyright notice for OSM and OS data.

Mapbox has a built-in feature https://docs.mapbox.com/mapbox-gl-js/api/markers/#attributioncontrol 

The message should include the OS message:

'Contains OS data © Crown copyright 2022'

And the OSM message

'© OpenStreetMap contributors' - or similar the OSM rules are more flexible  https://wiki.osmfoundation.org/wiki/Licence/Attribution_Guidelines

**Comment by mvl22** [comment]
These are already present.

Though it looks like one doesn't - I'll fix that up.

![Screenshot 2022-07-20 at 23 47 14](https://user-images.githubusercontent.com/361423/180095518-c3eaf7b8-31dc-44cb-b724-5afab17f4531.png)

![Screenshot 2022-07-20 at 23 47 04](https://user-images.githubusercontent.com/361423/180095520-0755e4e0-b9a1-44fe-a892-709a8ef8ea80.png)

**Comment by mem48** [comment]
Its missing on the OS outdoor which is the default map, so that why I didn't see it

**Comment by mvl22** [comment]
OK, after some investigation, it seems this is the only layer that is both vector and doesn't use the mapbox:// protocol. I believe the layers like `mapbox://styles/mapbox/streets-v11` must have a built-in attribution system, so I need to add this explicitly in this case.

**Comment by mvl22** [comment]
This was surprisingly hard to fix - the OS layer doesn't have built-in support for attribution in the way `mapbox://` protocol -based layers do, so the only way to support this is to add the attribution control manually, and ensure it is removed properly when switching to another layer.
