### ISSUE TITLE
Missing legend items from the pie chart

### ISSUE THREAD

**Issue by mem48** [SDCA-tool/sdca-website#39]
In the Emissions by type tab, the legend on the pie chart only goes from A0 to C2, missing C3 and C4.

It looks like they just run out of space

![image](https://user-images.githubusercontent.com/15819577/180406601-c4f2e4f4-7e19-4156-bd9d-ec4955da7594.png)

Also, we don't currently calculate all the parts of the footprint. See the confidence column in the table where some values are "not calculated"

It would make sense to not include these items on the pie chart. At the moment the R package returns a 0 for these values. I could change it to a NA to signify that it is missing data.

**Comment by mvl22** [comment]
> At the moment the R package returns a 0 for these values. I could change it to a NA to signify that it is missing data.

Can it be set to be a genuine NULL? That would be the most semantic value, correctly representing absence of data.

**Comment by mvl22** [comment]
I've now set to filter out rows with emissions as null, so I think this fixes the display problem also as we get fewer result lines now anyway.
